### ISSUE TITLE
Display Issue

### ISSUE THREAD

**Issue by Julia-Casciato** [thetriangle/wc#32]
![triangle](https://cloud.githubusercontent.com/assets/8583192/6216168/4912e052-b5d5-11e4-9e2a-5414ac91b044.PNG)

not sure why this is overlapping

**Comment by thenoelforte** [comment]
I'll look into it.

**Comment by thenoelforte** [comment]
When adding captions, make sure the `width=""` or `height=""` attributes are not set, otherwise, the image will be forced to be those sizes.
