### ISSUE TITLE
Solve disappearing thumbnail issue

### ISSUE THREAD

**Issue by thenoelforte** [thetriangle/wc#41]
Check size

Check format

**Comment by thenoelforte** [comment]
@lexxal were you the one who reported this?

**Comment by lexxal** [comment]
...yes

On Thursday, April 21, 2016, Noel Forté <notifications@github.com> wrote:

> @lexxal <https://github.com/lexxal> were you the one who reported this?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/thetriangle/wc/issues/41#issuecomment-213082030>
>


-- 
Alexandra Jones
Drexel University '18
Editor-In-Chief- *The Triangle*
(c) 717-836-2381
(e) awj27@drexel.edu

**Comment by thenoelforte** [comment]
is this still relevant?

**Comment by thenoelforte** [comment]
@lexxal says we're good on this.
